[profile.default]
src = "src"
out = "out"
libs = ["lib"]
no_match_contract = "CryticTester"

# known error codes are: ["unreachable", "unused-return", "unused-param", "unused-var", "code-size", "shadowing", "func-mutability", "license", "pragma-solidity", "virtual-interfaces", "same-varname"]
# additional warnings can be added using their numeric error code: ["license", 1337]
ignored_error_codes = ["license", "unused-return", "unused-param"]

verbosity = 3

# optimizer = true
optimizer_runs = 200

[rpc_endpoints]
localhost = "http://localhost:8545"

[etherscan]
unknownchain = { key = "ABCDEFG", url = "https://<etherscan-api-url-for-that-chain>" }

[fuzz]
runs = 1024
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
